### ISSUE TITLE
KotlinX.Coroutines build errors when targeting Android 12 (SDK 31)

### ISSUE THREAD

**Issue by ngpp564** [RadiusNetworks/flybuy-android-xamarin#12]
Hi, we are trying to target our Xamarin.Android project to Android 12 (SDK 31) and when we install the latest Radiusnetworks.Flybuy.Android (2.3.1) package, (https://www.nuget.org/packages/Radiusnetworks.Flybuy.Android/2.3.1)
and build the project we are getting numerous build errors aronund KotlinX.Coroutines related errors.

We are also seeing number of errors related to managed type
`The Java type kotlinx.coroutines.flow.SharingStarted is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.`

I have tried installing Xamarin.KotlinX.Coroutine.Core , Xamarin.KotlinX.Corouting.JVM and  other dependent packages manually, but I still run into the same issue.

I also tried downgrading the Flybuy package to 2.1.5, 2.1.4.2 and 2.1.4.1

We are currently on 2.1.4.1, and it works fine when we target Android 11(SDK 30), but we ran into these build errors as soon as we upgrade to Android 12 support.
![image](https://user-images.githubusercontent.com/16406838/179894386-3d22072b-563a-43e9-8605-47266f72b6d7.png)

**Comment by ajhewitt** [comment]
@ngpp564 I had some issues building the bindings with Android 12 support a few weeks ago. There's been some updates from Xamarin and I can try again to see if those have been resolved. I'll post an update here once I have things resolved.

**Comment by ajhewitt** [comment]
@ngpp564 I did a build of the SDK version you are currently using (2.1.4) with Android 12 support. Can you try this to see if it resolves this build error? Package available here: https://www.nuget.org/packages/Radiusnetworks.Flybuy.Android/2.1.4.3

I plan to publish the latest SDK with Android 12 support, but want to see if this issue is resolved by building the bindings you are currently using by targeting Android 12.

**Comment by ngpp564** [comment]
@ajhewitt I am still seeing the same issue.

**Comment by ajhewitt** [comment]
@ngpp564 it looks like you would need SDK version `2.3.0` or greater to get full Android 12 support. There appears to be some issues with the `2.3.1` SDK published on Nuget.org, so I'm rebuilding to bindings with the latest `2.5.3` SDK. There are a lot of errors when generating the bindings and I'm in the process of resolving these. I'll keep you posted on progress.

**Comment by ajhewitt** [comment]
I've published an initial release of the Android SDK `2.5.1` bindings. This is the latest Android  SDK built for Android 12 and builds in my example app targeting API 31. I'm seeing a runtime error that should be resolved by adding the missing library to the app. I plan to resolve this in the bindings and will push another point release when fixed.

**Comment by ajhewitt** [comment]
Build/runtime has been verified with Android 12 using `2.6.2.2` release.
